### ISSUE TITLE
about max_label_len & mask generation

### ISSUE THREAD

**Issue by richjjj** [noahzhy/KR_LPR_TF#1]
Very lucky to see such a great work, I would like to implement it in pytorch, but I have a couple of doubts:
1. the difference between `time_steps` and `max_label_len`, there are different assignments in different files.
2. how to generate the mask, it's not the same as the original author's.
3. I can't find an implementation of `random_brightness`.

**Comment by noahzhy** [comment]
This project has not completed yet, even model architecture is changing now.

**Comment by richjjj** [comment]
Thank you for the update，have a nice day

**Comment by noahzhy** [comment]
This project has been turned into the Jax version, all done and updated.
