### ISSUE TITLE
float32 tflite export

### ISSUE THREAD

**Issue by qkqk772** [noahzhy/KR_LPR_TF#2]
Thank you for your great work,

I successfully used the int8 .tflite file provided in the repository, and it predicted well. 
However, after exporting a .tflite file with the float32 type, it began predicting completely strange values. 

How can I export a float32 .tflite file that outputs normal values?

**Comment by noahzhy** [comment]
This repository has been converted to the JAX version to support distributed training on CPU/GPU/TPU etc.

If you are looking for the float32 tflite model, download it [here](https://huggingface.co/spaces/noahzhy/KR_LPR/blob/main/model.tflite). It's exported via above Jax project. Also you can just test it on hugging face easily.
