### ISSUE TITLE
Information about the Datasets Used for Training

### ISSUE THREAD

**Issue by ssggu** [noahzhy/KR_LPR_TF#3]
Hello, thank you for sharing your project.
I am curious about the number of license plate images used in the training of the demo model you shared, and what datasets were used.
If it is difficult to share, I would appreciate it if you could at least share the number of license plate images used for training.

**Comment by noahzhy** [comment]
The training dataset comprised 100,000 license plate images, including both real and synthetic data. The ratio of real to synthetic data was 1:3. As real license plate data is private and cannot be shared publicly, details of this project will be released in an upcoming paper. Please keep an eye out if you're interested in learning more.
